# This is a basic workflow to help you get started with Actions
name: CI
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        env:
          PEM: batata
          
      - name: echo
        run: echo $PEM
      - name: Updating
        run: sudo apt update
      - name: Ansible
        run: sudo apt install ansible
      - name: install tree
        run: sudo apt install tree
      - name: tree
        run: sudo tree
      - name: key
        run: mv ansible/gfr42.pem .
      - name: chmod
        run: chmod 400 gfr42.pem
      - name: tree
        run: sudo tree
      - name: Run playbook
        run: ansible-playbook ansible/playbook.yaml --private-key=gfr42.pem --inventory-file ansible/ci_cd.ini
